version: '3.3'

services:
  # Master-сервер
  seaweedfs-master:
    image: chrislusf/seaweedfs
    container_name: seaweedfs-master
    command: "master"
    ports:
      - "9333:9333"
    volumes:
      - ./seaweedfs_data/master:/data
    restart: always

  # Volume-сервер для хранения данных
  seaweedfs-volume:
    image: chrislusf/seaweedfs
    container_name: seaweedfs-volume
    command: "volume -mserver=seaweedfs-master:9333 -dir=/data"
    ports:
      - "8080:8080"
    depends_on:
      - seaweedfs-master
    volumes:
      - ./seaweedfs_data/volume:/data
    restart: always

  # Filer
  seaweedfs-filer:
    image: chrislusf/seaweedfs
    container_name: seaweedfs-filer
    command: "filer -master=seaweedfs-master:9333"
    ports:
      - "8888:8888"
    depends_on:
      - seaweedfs-master
    volumes:
      - ./seaweedfs_data/filer:/data
    restart: always
