{{- $dbConn := .Values.sharedSecret.dbConnStr | default (printf "postgres://%s:%s@postgres:5432/%s" .Values.sharedSecret.postgresUser .Values.sharedSecret.postgresPassword .Values.sharedSecret.postgresDatabase) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.sharedSecret.name }}
  labels:
    app.kubernetes.io/name: haltefest-shared-secrets
    app.kubernetes.io/part-of: haltefest
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.sharedSecret.postgresUser | quote }}
  POSTGRES_PASSWORD: {{ .Values.sharedSecret.postgresPassword | quote }}
  POSTGRES_DB: {{ .Values.sharedSecret.postgresDatabase | quote }}
  DB_CONN_STR: {{ $dbConn | quote }}
  GIGACHAT_AUTH_KEY: {{ .Values.sharedSecret.gigachatAuthKey | quote }}
  GIGACHAT_CLIENT_ID: {{ .Values.sharedSecret.gigachatClientId | quote }}
  GIGACHAT_CLIENT_SECRET: {{ .Values.sharedSecret.gigachatClientSecret | quote }}
