// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.857
package home

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/Cyr1ll/golang-templ-htmx-app/internal/service"
	"github.com/Cyr1ll/golang-templ-htmx-app/internal/view/layout"
)

func About(user *service.User) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"p-4\"><h1 class=\"text-2xl font-bold\">О нас</h1><p class=\"mt-2\">Добро пожаловать в наше приложение! Оно создано для того, чтобы помочь вам визуализировать и организовывать ваши данные в интерактивном и доступном для восприятия формате.</p><p class=\"mt-2\">Наша история начинается с идеи представить данные в графическом формате, что позволяет упростить восприятие взаимосвязей между различными элементами. Одним из основополагающих подходов для таких визуализаций является теория фреймов Марвина Минского.</p><p class=\"mt-2\">Марвин Минский, один из пионеров в области искусственного интеллекта, предложил теорию фреймов как модель для представления знаний. Фреймы — это структуры, которые используются для хранения информации о типах объектов и событий, что позволяет моделировать знания о мире. В контексте отображения данных эта теория помогает нам создавать графы, где каждый узел представляет собой фрейм, а связи между ними — отношения, которые описывают, как эти фреймы связаны.</p><p class=\"mt-2\">История инфицированного отображения данных восходит к попыткам создать структуры, которые бы отражали сложные взаимосвязи между объектами, моделируя их как фреймы. Идея Минского заключалась в том, чтобы сделать такие фреймы гибкими и адаптивными, так как в реальном мире данные часто меняются и могут иметь различные контексты.</p><p class=\"mt-2\">Используя фреймы для создания графов, мы можем представлять не только объекты и их свойства, но и взаимодействия между ними, что делает понимание данных более интуитивным и логичным. Мы верим, что такой подход помогает пользователям лучше воспринимать информацию, упрощая сложные концепты и облегчая их анализ.</p><p class=\"mt-2\">Спасибо, что выбрали наше приложение. Мы надеемся, что оно будет полезным инструментом для вас, и планируем продолжать развивать его функциональность в будущем!</p></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layout.Base(layout.BaseProps{
			Title: "О нас",
			User:  user,
		}).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
