// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package home

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/Cyr1ll/golang-templ-htmx-app/internal/service"
	"github.com/Cyr1ll/golang-templ-htmx-app/internal/view/layout"
)

func Index(user *service.User, graphData interface{}) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"p-4\"><h1 class=\"text-2xl font-bold\">Добро пожаловать в мир унифицированных данных!</h1>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if user != nil {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<p class=\"mt-2\">Hello, ")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var3 string
				templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(user.Username)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/view/home/index.templ`, Line: 16, Col: 54}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "!</p>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<p></p><p class=\"text-lg mt-4\">Этот сайт позволяет пользователям работать с файлами в унифицированном формате.</p><p class=\"text-lg mt-4\">Вы можете загружать файлы разных типов, размеров, количества.</p><p class=\"text-lg mt-4\">После загрузки ваши файлы будут отображать в унифицированном формате в виде графа, листья(конечные узлы) которого - файлы.</p><p class=\"text-lg mt-4\">Каждый файл будет связан со свой категорией, которая определяется автоматически!.</p><p class=\"text-lg mt-4\">Пройдите регистрацию и попробуйте сами!.</p><p class=\"text-lg mt-4\">Снизу представлен пример работы.</p><div id=\"graphContainer\" class=\"mt-4\"></div><p class=\"text-lg mt-4\">Пример графа.</p></div><script>\n            var nodes = new vis.DataSet([\n                { id: 1, label: 'Username', shape: 'box' },\n                { id: 2, label: 'Category A' },\n                { id: 3, label: 'Category B' },\n                { id: 4, label: 'File 1' },\n                { id: 5, label: 'File 2' },\n                { id: 6, label: 'File 3' }\n            ]);\n\n            var edges = new vis.DataSet([\n                { from: 1, to: 2 },\n                { from: 1, to: 3 },\n                { from: 2, to: 4 },\n                { from: 3, to: 5 },\n                { from: 3, to: 6 }\n            ]);\n\n            var container = document.getElementById('graphContainer');\n            var data = {\n                nodes: nodes,\n                edges: edges\n            };\n            var options = {};\n            var network = new vis.Network(container, data, options);\n        </script>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layout.Base(layout.BaseProps{
			Title: "Main Page",
			User:  user,
		}).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
