# values/infra.yaml
sharedSecret:
  name: haltefest-shared-secrets
  postgresUser: myappuser
  postgresPassword: mypassword
  postgresDatabase: myapp
  dbConnStr: ""
  gigachatAuthKey: ""
  gigachatClientId: ""
  gigachatClientSecret: ""

infra:
  postgres:
    image: postgres:15
    port: 5432

  dragonfly:
    image: dragonflydb/dragonfly:v1.27.1
    port: 6379

  qdrant:
    image: qdrant/qdrant
    httpPort: 6333
    grpcPort: 6334

  ollama:
    image: ollama/ollama:0.20.2
    port: 11434
    preferredModels:
      - qwen2.5:0.5b
      - qwen2.5:1.5b
    temperature: 0.3
    numCtx: 4096
