helmDefaults:
  wait: true
  timeout: 900
  createNamespace: true

repositories:
  - name: seaweedfs
    url: https://seaweedfs.github.io/seaweedfs/helm

releases:
  - name: kafka
    namespace: haltefest
    chart: oci://registry-1.docker.io/bitnamicharts/kafka
    version: 26.8.0
    values:
      - ./values/kafka.yaml

  - name: seaweedfs
    namespace: haltefest
    chart: seaweedfs/seaweedfs
    version: 4.20.0
    values:
      - ./values/seaweedfs.yaml

  - name: haltefest-infra
    namespace: haltefest
    chart: ./charts/haltefest-infra
    needs:
      - haltefest/kafka
    values:
      - ./values/infra.yaml

  - name: haltefest-app
    namespace: haltefest
    chart: ./charts/haltefest-app
    needs:
      - haltefest/kafka
      - haltefest/seaweedfs
      - haltefest/haltefest-infra
    values:
      - ./values/app.yaml
