/** @type {import('tailwindcss').Config} */
module.exports = {
	content: {
		relative: true,
		files: [
			'../internal/view/**/*.templ',
			'../internal/view/**/*_templ.go',
			'../internal/view/**/*.go',
			'./src/**/*.html',
			'./src/**/*.js',
		],
	},
	safelist: [
		'navbar',
		'bg-primary',
		'text-primary-content',
		'menu',
		'menu-horizontal',
		'btn',
		'btn-primary',
		'btn-ghost',
		'btn-error',
		'btn-sm',
		'table',
		'table-zebra',
		'badge',
		'badge-sm',
		'badge-success',
		'badge-warning',
		'badge-error',
		'badge-info',
		'badge-ghost',
		'loading',
		'loading-spinner',
		'loading-sm',
		'link',
		'link-primary',
		'link-error',
	],
	theme: {
		extend: {},
	},
	plugins: [require('daisyui')],
}
